### ISSUE TITLE
I can't remove Death's Odium

### ISSUE THREAD

**Issue by Henrico326** [TinyModularThings/UniqueEnchantments#32]
I try to remove it with NBTExplorer but I can't, when I change the value of "Amount" and "Operation" to 0, they come back to me, but when I die again, I lose my heart and he returned "-16" and I can't improve my health, please help me, I'm using this save on an external server, I don't know if that changes anything.

**Comment by Xaikii** [comment]
With the 1.9 update we added a way to get back the Hearts (and potentially even get more)
https://github.com/TinyModularThings/UniqueEnchantments/wiki/Death%27s-Odium
make sure you're running Unique Enchantments 1.9.2 or 2.0

**Comment by Henrico326** [comment]
I can't do that because, I'm using version 1.9.0, and I can't update it because I'm hosting the world on aternos, and it doesn't let me update a mod from an entire modpack or send an updated version of the mod (I'm using RAD lite modpack)

**Comment by Xaikii** [comment]
This also work on 1.9.0
There were simply some bugs that were fixed in 1.9.2

**Comment by Henrico326** [comment]
Okay, but when the totem is activated and I defeat the wither in 10 seconds with a sword that deals 48 damage in the modpack, the hearts still don't come back, what should I do? sorry if i'm doing something wrong

**Comment by Xaikii** [comment]
It should.
Unique Enchantments supports ingame configs.
[inGame] pls go to: Mods --> Unique Enchantments --> Config
and search "Death's Odium" within the config a Value called "damage factor" should exist.
That Value is one of the bugs fixed in 1.9.2.
If that Value exists and is set to 0, the Packdev has disabled this Feature.
If this does not exist, contact the Modpack Author, to either fix the Configs or update the Mod (+ Modpack).

**Comment by Henrico326** [comment]
not have "damage factor", but can I solve this on my own? like to change something inside the files, and if have, please how i do this?

**Comment by Xaikii** [comment]
If as you said Aternos doesn't grant access to files... no, not on a server.
Regarding NBTExplorer, you can reset the value every time. Else I don't have a solution.

**Comment by Henrico326** [comment]
I can change some files like the playerdata, but when adding mods I can't, the only way is i just putting mod by mod instead of installing the entire modpack

**Comment by Xaikii** [comment]
Theoretically yes, but then you wouldn't have the configurations of the Pack or am I misunderstanding something?

**Comment by Henrico326** [comment]
apparently not, but I was wondering if there is another way to remove this curse by NBT in the playerdata, if I am not going to have to add mod by mod to update the mod

**Comment by Henrico326** [comment]
the playerdata always comes back with the curse when I die, is there anything to stop him coming back? sorry for many questions at once

**Comment by Henrico326** [comment]
well, I kind of did a "solution" for that, I used the scaling health mod and put the command "/ scalinghealth health add 10" (I used 10 life as an example) so I can add the hearts that Death's Odium removes

**Comment by Speiger** [comment]
@Henrico326 there is not much we can do for you. Since even if you find a bug and we patch it you can not update/edit it.
I would suggest you look into self hosting a server. There are plenty of hosting providers out there that charge less then 10 bucks for a decent playserver. If you want more control.
